name: urban_skies
description: "A sleek, modern weather forecast app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  shared_preferences: ^2.2.2
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assests/sun.png

flutter_native_splash:
  color: "#87CEEB"
  image: assests/sun.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
